---
# This is an example playbook to run the role
- name: Run the setup-fedora role
  hosts: localhost
  become: true
  become_user: kartik
  become_method: sudo
  roles:
    - role: ../setup-fedora
      vars:
        nvidia: true
        omz: false
        version: 38
