---
# This is an example playbook to run the role
- name: Run the setup-fedora role
  hosts: localhost
  become: true
  remote_user: kartik
  roles:
    - role: ../setup-fedora
      vars:
        nvidia: true
        omz: true
        docker: true
        version: 38
