# Create our many config files

- name: Create zshrc config from template
  ansible.builtin.template:
    src: templates/zshrc.j2
    dest: "{{ home_user }}/.zshrc"

- name: Ensure .ssh folder exists
  ansible.builtin.file:
    path: "{{ home_user }}/.ssh"
    state: directory
    mode: '0755'

- name: Create .ssh/config
  ansible.builtin.template:
    src: templates/ssh-config.j2
    dest: /home/{{ ansible_facts['env']['SUDO_USER'] }}/.ssh/config

- name: Create gitconfig
  ansible.builtin.template:
    src: templates/gitconfig.j2
    dest: "{{ home_user }}/.gitconfig"
