- name: Install nvidia drivers
  dnf:
    name: akmod-nvidia
    state: present

- name: Install the optional 64 bit & 32 bit CUDA and NVENC packages
  dnf:
    name: xorg-x11-drv-nvidia-cuda, xorg-x11-drv-nvidia-cuda-libs, xorg-x11-drv-nvidia-libs.i686
    state: present

- name: Install Vulkan
  dnf:
    name: vulkan
    state: present

- name: Install packges to enable video acceleration in media players
  dnf:
    name: vdpauinfo, libva-vdpau-driver, libva-utils
    state: present
