---
- name: Clone oh-my-zsh repo  # noqa: latest
  ansible.builtin.git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: "{{ home_user_path }}/.oh-my-zsh}"
  become: true
  become_user: "{{ home_username }}"

- name: Clone passion theme under ohmyzsh themes folder  # noqa: latest
  ansible.builtin.git:
    repo: 'https://github.com/ChesterYue/ohmyzsh-theme-passion.git'
    dest: "{{ home_user_path }}/.oh-my-zsh/themes/passion.zsh-theme"
  become: true
  become_user: "{{ home_username }}"

