---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: setup-fedora
    image: docker.io/fedora:36
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  yamllint .
